### ISSUE TITLE
Translation issue German

### ISSUE THREAD

**Issue by HDValentin** [freecycle/Translation#14]
![screenshot 2017-06-10 00 06 06](https://user-images.githubusercontent.com/1276955/26996175-20c49e02-4d71-11e7-8d8a-c45f34eeeb30.jpg)

"Try the forgotten password form" is untranslated.

**Comment by steevhise** [comment]
Thanks for pointing that out.  I think that was a text change that didn't make it into the .pot file. I will correct that.

**Comment by steevhise** [comment]
I have updated the pot file from current code. However, I think the sentence in question was already there:   https://github.com/freecycle/Translation/blob/master/freecycle.pot#L5641 - it is just not translated in the de.po file.

**Comment by HDValentin** [comment]
The sentenence was there and I've already translated it.

**Comment by steevhise** [comment]
hmm. seems to be a weird syntax error, perhaps caused by poedit or something.  
if you look at https://github.com/freecycle/Translation/blob/master/translations/de.po#L6663
you can see msgstr entry is blank, but then the translation is right after.
I guess I will hand-edit the file.
