### ISSUE TITLE
How to translate modtools

### ISSUE THREAD

**Issue by HDValentin** [freecycle/Translation#2]
For the frontend I have the freecycle.pot I import into the de.po. Should I import the moderatortools.pot into de.po also if I want to translate them? What is the "how-to" to start to translate modtools?

**Comment by steevhise** [comment]
freecycle.pot is a concatention of the catalogs from all the sites (groups, www, myf, etc), so there's no need to separately import them.  Modtools is something I'm currently working on at the top of my to-do list to get the rest of the templates translatable.  The "Files" and "Links" areas of the site are already in the .pot, but there's a bunch of code changes required before everything else is in there.  In another week or at most 2, it should be ready.  thanks for your patience!

**Comment by HDValentin** [comment]
So should we wait until you've finished your work?
Or could we start translating?

**Comment by steevhise** [comment]
If there are still a significant number of entries untranslated, feel free to get started. Thanks!

On Jan 23, 2015, at 11:34 AM, Valentin <notifications@github.com> wrote:

> So should we wait until you've finished your work?
> Or could we start translating?
> 
> —
> Reply to this email directly or view it on GitHub.
> 



Steev Hise | steev@detritus.net | http://detritus.net/steev
-----------------------------------------------------------------------------
"If knowledge is power, then the internet is full of completely useless power."
        - Brett Erlich

**Comment by HDValentin** [comment]
You mean from freecycle.pot? It is all translated.
